### ISSUE TITLE
Broken pychaste conda install

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/PyChaste#55]
**Summary**

* Recent changes in colab cause dependency resolution to fail during pychaste installation, resulting in the error below.

```
No package can be installed for pin: cudatoolkit 12.2.*

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = install(args, parser, "install")
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 547, in install
        solver.add_pin(final_spec)
    RuntimeError: No package can be installed for pin: cudatoolkit 12.2.*

`$ /usr/local/bin/mamba install -y -q -c pychaste -c conda-forge -c bioconda chaste`

  environment variables:
                 CIO_TEST=<not set>
COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer
COLAB_LANGUAGE_SERVER_PROXY=<set>
               CONDA_ROOT=/usr/local
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
               LD_PRELOAD=<not set>
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us
                          r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl
                          e-cloud-sdk/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               TCLLIBPATH=/usr/share/tcltk/tcllib1.20

     active environment : None
       user config file : /root/.condarc
 populated config files : /usr/local/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=6.1.58=0
                          __unix=0=0
       base environment : /usr/local  (writable)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/pychaste/linux-64
                          https://conda.anaconda.org/pychaste/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/6.1.58+ ubuntu/22.04.3 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by kwabenantim** [comment]
There are also issues installing in a normal conda environment, not only in Colab.

This appears to be a problem with dependency version alignment for the Python 3.11 package.

Installation is successful when Python 3.10 is specified:

```sh
mamba create -n pychaste-py310 -c pychaste -c conda-forge -c bioconda chaste python=3.10
```

Installation is successful for Python 3.11 when versions are specified for packages with newer versions that break the install:

```sh
mamba create -n pychaste-py311 -c pychaste -c conda-forge -c bioconda chaste python=3.11 boost-cpp=1.74 vtk=7.1.1
```

**Comment by kwabenantim** [comment]
The Python 3.11 conda package has been fixed with the following changes to the metadata in `info/index.json`:

```diff
--- a/index.json
+++ b/index.json
@@ -3,7 +3,7 @@
   "build": "py311h6d9115b_0",
   "build_number": 0,
   "depends": [
-    "boost-cpp",
+    "boost-cpp >=1.68,<1.76",
     "hdf5 * mpi_mpich*",
     "hdf5 >=1.12.2,<1.12.3.0a0 mpi_mpich_*",
     "libgcc-ng >=12",
@@ -14,13 +14,13 @@
     "metis >=5.1.0,<5.1.1.0a0",
     "mpich >=4.0.3,<5.0a0",
     "numpy",
-    "parmetis",
+    "parmetis >=4",
     "petsc >=3.17.4,<3.18.0a0 real_*",
     "petsc4py",
     "python >=3.11,<3.12.0a0",
     "python_abi 3.11.* *_cp311",
     "sundials >=5.8.0,<5.9.0a0",
-    "vtk",
+    "vtk 7.1.1.*",
     "xerces-c >=3.2.4,<3.3.0a0",
     "xsd 4.*",
     "xvfbwrapper"
```

The conda installation now works correctly:
```
mamba create -n pychaste-env -c pychaste -c conda-forge -c bioconda chaste
```
